### ISSUE TITLE
For debugging assert are easier to debug than assert_utils, as It logs failing tests where with assert utils it logs assert_util file.

### ISSUE THREAD

**Issue by ketanarlulkar** [Seagate/cortx-test#1392]
For debugging assert are easier to debug than assert_utils, as It logs failing tests where with assert utils it logs assert_util file.
Any specific reason for promoting this?

_Originally posted by @kachhwahadivya in https://github.com/Seagate/cortx-test/pull/1390#discussion_r834923775_

For keeping uniformity, need to update assert_utils to print all test details in case of failure

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-29707. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by hessio** [comment]
Can this issue be closed since the PR #1390 was merged?

**Comment by kachhwahadivya** [comment]
assert is available to use. Hence closing this one
