### ISSUE TITLE
Too many local variables (18/15)

### ISSUE THREAD

**Issue by mukul-seagate11** [Seagate/cortx-test#1512]
#### Occurred on:
+ **Commit**:  eb253fce47c7ebbdc60d6a52395c9e9a06283802
+ **File**:    [drunner.py](https://github.com/Seagate/cortx-test/blob/eb253fce47c7ebbdc60d6a52395c9e9a06283802/drunner.py)
+ **LineNum**: [205](https://github.com/Seagate/cortx-test/blob/eb253fce47c7ebbdc60d6a52395c9e9a06283802/drunner.py#L205)
+ **Code**:    `def develop_execution_plan(rev_tag_map, selected_tag_map, skip_test, test_map, tickets):`

    
#### Currently on:
+ **Commit**:  41b4f8c466360f1e8b4d34416158fe91246e9cfd
+ **File**:    [drunner.py](https://github.com/Seagate/cortx-test/blob/41b4f8c466360f1e8b4d34416158fe91246e9cfd/drunner.py)
+ **LineNum**: [237](https://github.com/Seagate/cortx-test/blob/41b4f8c466360f1e8b4d34416158fe91246e9cfd/drunner.py#L237)

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31191. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
