### ISSUE TITLE
Refactor _add_parameters 

### ISSUE THREAD

**Issue by seagate-sarang-sawant** [Seagate/cortx-test#1570]
Simplify this method into multiple methods.

_Originally posted by @seagate-sarang-sawant in https://github.com/Seagate/cortx-test/pull/1569#discussion_r876870125_

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31526. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.

**Comment by shailesh-vaidya** [comment]
Closing as an obsolete
