### ISSUE TITLE
Remove s3bench logs location from the project root

### ISSUE THREAD

**Issue by seagate-sarang-sawant** [Seagate/cortx-test#1598]
### Problem

S3bench logs are bloating in cortx-test root folder precisely in the CWD instead of log folder. Collect s3bench logs into test log folder itself. 

### Expected behavior

Collect s3bench logs into test log folder itself. 

### How to reproduce

Run sanity test cases.

### Deployment information

Single test client i.e Corbot on CentOS 7+

**Comment by cortx-admin** [comment]
For the convenience of the Seagate development team, this issue has been mirrored in a private Seagate Jira Server: https://jts.seagate.com/browse/CORTX-31661. Note that community members will not be able to access that Jira server but that is not a problem since all activity in that Jira mirror will be copied into this GitHub issue.
